name: parser-drf-local

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_HOST=${SQL_HOST}
      - POSTGRES_PORT=${SQL_PORT}

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]

volumes:
  postgres-data:
