# Generated by Django 5.1.1 on 2024-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=200)),
                ('article_author', models.CharField(max_length=200)),
                ('result', models.JSONField()),
            ],
        ),
    ]
