# Generated by Django 5.1.1 on 2024-09-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_listarticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_profile', models.URLField(help_text='Ссылка на профиль автора')),
                ('author', models.CharField(help_text='Имя автора')),
                ('author_rating', models.CharField(help_text='Рейтинг автора')),
                ('title', models.CharField(help_text='Название статьи')),
                ('content', models.CharField(help_text='Содержание стать')),
                ('date', models.CharField(help_text='Дата публикации')),
                ('rating', models.CharField(help_text='Рейтинг статьи')),
                ('bookmarks', models.CharField(help_text='Количество добавления в закладки')),
                ('comments', models.CharField(help_text='Комментарии')),
            ],
        ),
    ]
