# Generated by Django 5.1.1 on 2024-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_searcharticles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ListArticles',
        ),
        migrations.AlterField(
            model_name='searcharticles',
            name='parsing_options',
            field=models.CharField(choices=[('list', 'list_of_articles'), ('first', 'first_article')], default='first', help_text='Как парсить'),
        ),
        migrations.AlterField(
            model_name='searcharticles',
            name='searching_filter',
            field=models.CharField(choices=[('relevance', 'relevance'), ('date', 'date'), ('rating', 'rating')], default='relevance', help_text='Способ фильтрации'),
        ),
    ]
