# Generated by Django 5.1.1 on 2024-09-18 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_delete_article_delete_listarticles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_link', models.URLField(help_text='Ссылка на статью')),
                ('title', models.CharField(help_text='Название статьи')),
                ('author_profile', models.URLField(help_text='Ссылка на профиль автора')),
                ('author', models.CharField(help_text='Имя автора')),
                ('author_rating', models.CharField(help_text='Рейтинг автора')),
                ('content', models.CharField(help_text='Содержание стать')),
                ('date', models.CharField(help_text='Дата публикации')),
                ('rating', models.CharField(help_text='Рейтинг статьи')),
                ('bookmarks', models.CharField(help_text='Количество добавления в закладки')),
                ('comments', models.CharField(help_text='Комментарии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='SearchArticles',
            new_name='HistorySearch',
        ),
        migrations.DeleteModel(
            name='OneArticle',
        ),
    ]
