# Generated by Django 5.1.1 on 2024-10-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_article_search_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='historysearch',
            options={'ordering': ['-id']},
        ),
    ]
