# Generated by Django 5.1.1 on 2024-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_alter_article_options_alter_historysearch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.CharField(blank=True, help_text='Рейтинг статьи', null=True),
        ),
    ]
