# Generated by Django 5.1.1 on 2024-09-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_onearticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searching_key', models.CharField(help_text='Поисковый запрос')),
                ('searching_filter', models.CharField(choices=[('relevance', 'relevance'), ('date', 'date'), ('rating', 'rating')], default='relevance')),
                ('parsing_options', models.CharField(choices=[('list', 'list_of_articles'), ('first', 'first_article')], default='first')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
